= CloudBees action: Invoke AWS Lambda function

Use this action to invoke a function in AWS Lambda serverless architecture.
Run code in AWS Lambda without provisioning or managing servers.

== Prerequisites

Make sure to initialize the connection using your AWS credentials, by adding the following to your YAML file:

[source,yaml]
----
      - name: Configure AWS credentials
        uses: cloudbees-io/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_SECRET_KEY }}
          aws-region: eu-west-3
----

Refer to link:https://github.com/cloudbees-io/configure-aws-credentials[CloudBees action: Configure AWS credentials] for more information.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `function-name`
| String
| Yes
| The instruction set architecture that the function supports.

| `parameters`
| JSON
| No
| The input you want to provide to your Lambda function, formatted as JSON data in key/value pairs.

|===

== Usage example

In your YAML file, add:

[source,yaml]
----
      - name: Invoke AWS lambda function
        id: invokeLambdaFunction
        uses: cloudbees-io/lambda-invoke-function@v1
        with:
          function-name: my-function

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
